### PR TITLE
chore: go-ipfs-0.13.0 and go 1.17

### PR DESCRIPTION
**Pull request by ajnavarro**
Update dependencies to support the latest IPFS version and bump go version to 1.17.

~~DO NOT MERGE until IPFS final 0.13.0 version is released.~~ Updated to IPFS 0.13.0.

### CODE REVIEW

**Comment by ajnavarro** [comment]
it supersedes #105

**Comment by BigLep** [comment]
Blocked until https://github.com/ipfs/go-ipfs/pull/8954 gets addressed.

**Comment by ajnavarro** [comment]
Blocked by https://github.com/ipfs/go-ipfs-http-client/pull/160

**Review by lidel — COMMENTED** [review]
Unblocked!  Switched to go-ipfs-http-client  [v0.4.0](https://github.com/ipfs/go-ipfs-http-client/releases/tag/v0.4.0). 


CI is green, lgtm.

**Pull request merged**
